[tools]
elixir = "1.18.4-otp-27"
erlang = "27.3"
node = '22'

[hooks]
# Enabling corepack will install the `pnpm` package manager specified in your package.json
# alternatively, you can also install `pnpm` with mise
postinstall = 'npx corepack enable'

[settings]
# This must be enabled to make the hooks work
experimental = true

[tasks.log]
run = '''
aws logs tail '/ecs/admin' --follow --profile $1
'''

[tasks.remote]
usage = '''
arg "profile" "AWS profile name" default="dev"
'''
run = [
    'aws sts get-caller-identity --profile $usage_profile',
    'aws ecs execute-command --cluster graasp-$usage_profile --task $(aws ecs list-tasks --cluster graasp-$usage_profile --service admin --query "taskArns[0]" --output text --profile $usage_profile) --container admin --command "/app/bin/admin remote" --interactive --profile $usage_profile'
]

[tasks.backend-dev]
run = "mix phx.server"

[tasks.frontend-install]
dir = "frontend"
run = "pnpm install"
description = "install frontend dependencies"

[tasks.frontend-dev]
depends = ["frontend-install"]
dir = "frontend"
run = "pnpm run dev"
description = "start the frontend server in development mode"

[tasks.dev]
depends = ["backend-dev", "frontend-dev"]
description = "start the backend and frontend servers in development mode"
