apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: graasp
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  clusterIP: None  # headless — stable DNS postgres-0.postgres.graasp.svc.cluster.local
