defmodule Admin.Notifications.Pixel do
  @moduledoc """
  Represents a notification pixel used for tracking in emails.
  """

  use Admin.Schema
  import Ecto.Changeset

  schema "notification_pixels" do
    # the pixel id is given by Umami, it is not generated by us.
    field :name, :string
    field :slug, :string

    belongs_to :notification, Admin.Notifications.Notification

    timestamps()
  end

  def changeset(pixel, attrs) do
    pixel
    |> cast(attrs, [:id, :slug, :name, :notification_id])
    |> validate_required([:id, :slug, :name, :notification_id])
  end
end
