import Config

# Configure your database
config :admin, Admin.Repo,
  username: "graasper",
  password: "graasper",
  hostname: "localhost",
  database: "graasp",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :admin, AdminWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "WUz/cy0PS0UQvcwpItcpTMMKiZRrirYhEQttRxpaRuyZm1PkK87Yz6vcCgr9MKbP",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:admin, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:admin, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :admin, AdminWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/admin_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :admin, dev_routes: true

# Set the File Items bucket name
config :admin, :file_items_bucket, "file-items"

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

config :ex_aws, :s3,
  scheme: "http://",
  host: "s3.garage.localhost",
  port: 3900,
  region: System.get_env("AWS_REGION", "garage"),
  # If using custom endpoints like LocalStack or MinIO, path_style: true is often necessary.
  path_style: true

# Define the base host to use
config :admin, :base_host, "localhost:3114"
# define the backend host to use
# NOTE: We currently define a host for both the client and the backend event though they are the same domain in production.
#       This is because in development the "domain" is the vite dev server which can forward calls to the backend via the vite proxy.
#       While testing, it was discovered that requests made from Elixir could not reach the vite proxy.
#
#       In the future, if we change the setup and the entity that handles the "domain" in local dev is able to forward the requests to the backend correctly, this can be removed
config :admin, :backend_origin, "http://localhost:3001"

# Publication index (development defaults)
config :admin, :publication_reindex_headers, [{"meilisearch-rebuild", "secret"}]
