defmodule Admin.OpentelemetryEcto do
  @moduledoc """
  A wrapper around OpentelemetryEcto that filters out queries generated by Oban.
  """

  def setup(event_prefix, config \\ []) do
    event = event_prefix ++ [:query]

    :telemetry.attach({OpentelemetryEcto, event}, event, &__MODULE__.handle_event/4, config)
  end

  @doc false
  def handle_event(event, measure, %{options: options} = meta, config) do
    if Keyword.has_key?(options, :oban_conf) do
      :ok
    else
      OpentelemetryEcto.handle_event(event, measure, meta, config)
    end
  end
end
