name: Deploy Graasp perform to development environment

# Control when the action will run.
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
      - main

  # Triggers the workflow on closed pull request events only for the main branch
  pull_request:
    branches: [main]
    types: [closed]

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_OPTIONS: '--max_old_space_size=4096'

jobs:
  graasp-deploy-s3-workflow:
    name: Graasp Player
    # Reference reusable workflow file. Using the commit SHA is the safest for stability and security
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3.yml@e8d867feae69292a412f781299ade402e047b7a4
    with:
      build-folder: 'build'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ secrets.AWS_REGION_DEV }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_GRAASP_PERFORM_DEV }}
      cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_GRAASP_PERFORM_DEV }}
      api-host: ${{ secrets.REACT_APP_API_HOST_DEV }}
      port: ${{ secrets.PORT }}
      show-notifications: ${{ secrets.SHOW_NOTIFICATIONS }}
      authentication-host: ${{ secrets.REACT_APP_AUTHENTICATION_HOST_DEV }}
      graasp-compose-host: ${{ secrets.REACT_APP_GRAASP_COMPOSE_HOST_DEV }}
