name: tests and coverage
on: [push]
jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install packages
        run: yarn 

      - name: jest test
        run: yarn test

