name: Cypress tests
on:
  push:
    branches:
      - "main"
  merge_group:
  pull_request:

jobs:
  test:
    concurrency: cypress-${{ github.head_ref || github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Build
        run: yarn build

      - name: Component Tests 🧪
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: chrome

      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if a test failed
      - name: Upload Screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
