name: cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        # network-concurrency 1 is necessary to avoid errors when using github packages
        run: yarn cache clean && rm yarn.lock && yarn install --network-concurrency 1

      - name: cypress run
        uses: cypress-io/github-action@v2
        env:
          REACT_APP_API_HOST: ${{ secrets.REACT_APP_API_HOST }}
          REACT_APP_NODE_ENV: test
        with:
          install: false
          config: baseUrl=http://localhost:3000
          start: yarn start:ci
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 180
          browser: chrome
          headless: true
          quiet: true

      - name: coverage report
        run: npx nyc report --reporter=text-summary
